### ISSUE TITLE
Recommend ESLint for contributors

### ISSUE THREAD

**Issue by ZacharyRSmith** [exercism/xjavascript#101]
If we are going to recommend ESLint to exercism users (per an old issue and pull request I made today), then I think we should recommend it to contributors.

**Comment by kytrinyx** [comment]
Actually, maybe we can start by just recommending it to contributors, and applying it across the board here. Then we might know a bit more about whether or not we like it enough to suggest it to exercism users.

**Comment by ZacharyRSmith** [comment]
That's a good idea, and why you're the boss! ; )

Zachary Smith

**Comment by kytrinyx** [comment]
Hah. You'd be surprised. I think I'm only the boss because I keep showing up.

**Comment by ZacharyRSmith** [comment]
So, after a few days of running JSHint and ESLint on my code (with default settings), my vote is for JSHint. Because:

jshint points out missing semicolons, eslint doesn't.
jshint suggests using === instead of ==, eslint doesn't.

I can't speak for ESLint being "better" due to its being more configurable than JSHint, because I haven't worked with configurations. However, as I'm guessing most contributors on here are budding developers and don't want to get bogged down in configs (like me), then I think the linter with the best default configs would be an important factor. This seems to be JSHint.

**Comment by kytrinyx** [comment]
I think that is the best argument I've heard so far. Let's do it!

**Comment by ZacharyRSmith** [comment]
Update: I listened to a podcast on ESLint, and I believe you have to set some "run default lint checks" to true. I never configured my ESLint, which would explain why it wasn't catching the things JSHint was, as I referenced in my comment above.

**Comment by kytrinyx** [comment]
Oh, neat. That makes ESLint sound promising.

**Comment by matthewmorgan** [comment]
This is now in the intro docs for the language track, so I'm going to close this issue.
