### ISSUE TITLE
Wordcount is different from python or java

### ISSUE THREAD

**Issue by jmluy** [exercism/xjavascript#109]
Tests for word count is different in that it doesn't normalize to lowercase or even strip special characters.  It's not mentioned in the readme file but It might be better to have similar tests.

**Comment by kytrinyx** [comment]
Yeah, the word count exercise has evolved a bit over time. This might be a good time to extract the best test cases into a [shared set of metadata](https://github.com/exercism/todo/issues/7) so that the various tracks can [write generators](https://github.com/exercism/todo/issues/8)

**Comment by wobh** [comment]
It seems to me that, ideally, the word count test should be indifferent to the method of normalizing. Just did a PR to the xpython about this.

**Comment by kytrinyx** [comment]
Agreed--I really like that change.
