### ISSUE TITLE
Some tests do not follow conventional ordering of actual/expected

### ISSUE THREAD

**Issue by ZacharyRSmith** [exercism/xjavascript#111]
In the Jasmine testing framework, it is convention to

```javascript
expect(actual).fn(expected)
```

But Accumulate's tests are:

```javascript
expect(expected).fn(actual)
```
causing error messages to be confusing.

**Comment by kytrinyx** [comment]
Good catch. I've gotten myself all turned around between Ruby and Go for this reason: Ruby asserts with `expected -> actual`, but go asserts with `actual -> expected` (or _got/want_ as they say).

**Comment by ZacharyRSmith** [comment]
I fixed accumulate's tests in #113 , but I remember seeing this error in other exercises

**Comment by kytrinyx** [comment]
Yeah, I'll leave this open until we have verified that all the tests follow the idiom for javascript/jasmine.

**Comment by wilmoore** [comment]
:+1: - thanks for fixing @ZacharyRSmith. Not sure how I managed to FUBAR the tests but glad you caught/corrected that.

**Comment by ZacharyRSmith** [comment]
( :

**Comment by kytrinyx** [comment]
Is there anything left to do on this? What are the steps to verify? If we can describe the problem and how to check an exercise and how to fix it, then we can label this with "good first patch" a bunch of people could help out. We could also script something so we have one ticket per exercise to check, which would make it much easier to keep track of whether or not we've checked everything.

**Comment by rchavarria** [comment]
I think all exercises must be verified, I think I can find the time to have a list of exercises not following the convention.

I think @ZacharyRSmith described the problem correctly in the first comment. We could also include two code examples (the conventional one Vs the non-conventional one).

I also agree of having an issue labeled as "good first patch" for each exercise not following the convention. But I have no idea about having a script to create those issues (I think it should be *easy* to create one).

**Comment by kytrinyx** [comment]
I make scripts like this a lot. I'll post a suggestion here in a few minutes.

**Comment by kytrinyx** [comment]
Create an `ISSUE.md` file with something like this:

```
PLACEHOLDER:  verify ordering of actual/expected

```



```
for dir in $(git grep -l error | cut -d/ -f1 | uniq); do
        MSG=$(cat ISSUE.md | sed -e "s/PLACEHOLDER/$dir/")
        hub issue create -m "$MSG" -l "good first patch"
done
```

If you stick run this from `xjavarscript/exercises/` and `ISSUE.md` is also in the same directory, then this should work. It uses https://github.com/github/hub

**Comment by rchavarria** [comment]
Whoooo!! That's awesome!!

Not too bad, after being banned for a little:

    Error creating issue: Forbidden (HTTP 403)
    You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.

**Comment by kytrinyx** [comment]
Haha, it actually helps if you create a github user token and then auth in `hub` with it.

**Comment by rchavarria** [comment]
All exercises have been reviewed and those not following the convention have been fixed. Great job @ireddick!!

I'm going to close this issue :tada:
