### ISSUE TITLE
Improve test names in Gigasecond problem

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#126]
PR #125 adds a new test, but test names are not descriptive at all.

[Gigasecond on ECMAScript track](https://github.com/exercism/xecmascript/blob/master/gigasecond/gigasecond.spec.js) has better test names, but they test something slightly different. At least, they could serve as inspiration.

**Comment by kytrinyx** [comment]
If you find good test names, then perhaps we could improve the generator here:
https://github.com/exercism/x-common/blob/master/gigasecond.json

/cc @mikeyjcat

**Comment by rchavarria** [comment]
Actual test names are these:

- tells a gigasecond anniversary since midnight
- tells the anniversary is next day when you are born at night
- even works before 1970 (beginning of Unix epoch)
- make sure calling "date" doesn't mutate value

I think this issue can be closed.

@mikeyjcat What do you think about them?
