### ISSUE TITLE
All exercises should require a homogeneous structure to be exported

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#128]
Take a look at [exercism/exercism.io issue #2304](https://github.com/exercism/exercism.io/issues/2304). It talks about requiring the user to export a homogeneous structure for all exercises.

Some require the user to export a constructor function:

```
var Bob = function() {};
Bob.prototype.hey = function(input) { ... }
module.exports = Bob;
```

Some require to export an object:

```
var Hamming = {
    compute: function(A, B) { ... }
}
module.exports = Hamming;
```

Some require to export different things.

Could we first agree on what structure should exercises require to export?

**Comment by matthewmorgan** [comment]
I agree there should be more consistency, although I think it's worth
pointing out that wrestling with the output formats did help me sharpen my
understanding of modules.

On Thu, Nov 12, 2015 at 11:32 AM, Rubén Chavarría <notifications@github.com>
wrote:

> Take a look at exercism/exercism.io issue #2304
> <https://github.com/exercism/exercism.io/issues/2304>. It talks about
> requiring the user to export a homogeneous structure for all exercises.
>
> Some require the user to export a constructor function:
>
> var Bob = function() {};
> Bob.prototype.hey = function(input) { ... }
> module.exports = Bob;
>
> Some require to export an object:
>
> var Hamming = {
>     compute: function(A, B) { ... }
> }
> module.exports = Hamming;
>
> Some require to export different things.
>
> Could we first agree on what structure should exercises require to export?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xjavascript/issues/128>.
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by kytrinyx** [comment]
How about making the format consistent for the first 10 or 12 exercises, and then letting things be more inconsistent after people have gotten a few successes?

**Comment by matthewmorgan** [comment]
That sounds good.  That way they'll have some confidence in the internals
of their solution.

On Thu, Nov 12, 2015 at 5:21 PM, Katrina Owen <notifications@github.com>
wrote:

> How about making the format consistent for the first 10 or 12 exercises,
> and then letting things be more inconsistent after people have gotten a few
> successes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/exercism/xjavascript/issues/128#issuecomment-156255014>
> .
>



-- 
Matt Morgan
Director of Technology
Dulcet Software LLC
(734) 926-8142

**Comment by rchavarria** [comment]
It seems a much more affordable work to make *only* the first 12 exercises consistent than make all of them.

I wouldn't like to turn this into a discussion about using *classes* Vs not using them, but we should decide a estructure to export.

My proposition is the following. From the point of view of tests (the only code users see at the beginning), I would like to have them this way, using the `new` keyword:

```
// ...
var Bob = require('./bob');
// ...
it('some test', function () {
  var bob = new Bob();
});
// ...
```

There are two approaches that could make this test code to work: a *classy* one, and a *no-classy*:

```
// classy approach
function Bob() {}
Bob.prototype.hey = function () { ... };
module.exports = Bob;
```

```
// no classy approach
function Bob () {
  function hey() { ... }
  return {
    hey: hey
  };
}
module.export = Bob;
```

**Comment by kytrinyx** [comment]
I like that two approaches will pass the tests with that approach.

**Comment by matthewmorgan** [comment]
@rchavarria 'classy' vs 'no classy' approach -- *en broma*, no?  Is that the right phrase?

This seems like a good tack to me too.  I think one of the challenges of learning a new language is getting a handle on the environment and the tools, plus how much time is spent adapting to legacy code or integrating with APIs you didn't write?

**Comment by rchavarria** [comment]
@matthewmorgan yep, it was more or less a joke, and yes *en broma* is the right phrase. You know I would favor a *classy* approach, but I'm slowly appreciating other approaches, to avoid using `this` and learning a more JavaScript-way of doing things.
