### ISSUE TITLE
Broken links in documentation?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjavascript#137]
I got this email today:

-------

Just wanted to report a broken link in this page:
http://help.exercism.io/getting-started-with-javascript.html

the link should be http://ESLint.org while it's
http://help.exercism.io/ESLint.org.

Actually it seems all 3 of links in this sentence is broken:
*The old standard linter for JavaScript is JSLint. However, it is
controversially picky. JSHint is another popular linter. We suggest using
ESLint, which is more customizable than either JSLint or JSHint, and is
well-run.*

---------

This documentation has been moved to the exercism.io/languages/javascript page (documentation taken from the `./docs` directory in this repository.

Would someone verify that the `./docs` links are correct?

**Comment by matthewmorgan** [comment]
Fixed by #138
