### ISSUE TITLE
Treating functions as second class citizens

### ISSUE THREAD

**Issue by cmstead** [exercism/xjavascript#150]
I have noticed that even the earliest problems now require a prototypal setup before solving the problems.  This is not idiomatic Javascript because functions are first class citizens. Although the OO aspect of Javascript is important, I think using objects to wrap functions is unnecessary. Along with adding unnecessary cognitive overhead, it also misses a very important aspect of Javascript, specifically, closures. Perhaps some tests could be set up to necessitate OO principles while others could use functional principles.

In the end, I understand this is built based on opinions other than my own, so I am willing to accept "it is the way it is," but I didn't see any issues raised around this concern, so I wanted to get a temperature read on this.

Also, I would be willing to do the conversion work for the tests if people like this direction, so let me know and I can PR the changes necessary if desired.

**Comment by rchavarria** [comment]
Thanks @cmstead for your comments. This is a very controversial subject in JavaScript. Sorry if you feel that exercises don't take the functional programming side of JavaScript too seriously.

This subject was addressed on issue #128. In the end, we decided to make first exercises in a way that promotes the use *constructor functions*. There are lots of OO languages out there and this could help other users to start playing with JavaScript.

There is another reason. This approach allows users to solve exercises in two ways:

```
// constructor functions and prototypes
function Bob() {
   this.name = 'Bob';
}
Bob.prototype.hey = function () { ... };
module.exports = Bob;

// factory functions, avoid use of this
function Bob () {
  function hey() { ... }
  return {
    hey: hey
  };
}
module.export = Bob;
```

I hope you like more the second approach. It may not be as functional as you like, but it allows you to create `Bob` objects (or instances) without using `new` and the implementation avoids the use of `this`. This is an approach recommended by Douglas Crockford.

**Comment by cmstead** [comment]
@rchavarria Thanks for the follow up. I was trying not to come off too strongly since I understand that there were likely reasons. I appreciate the quick response and I understand the perspective you are taking with this. I'll go ahead and close my issue. : )

**Comment by rchavarria** [comment]
Nice! If you keep working on exercises, I'm sure you'll find some that don't necesarily force you to write OO-like JavaScript :wink:
