### ISSUE TITLE
Create test pattern in `config.json` to help exercism.io to identify files that contain tests

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#154]
There is a small bug in exercism.io ([exercism.io#2610](https://github.com/exercism/exercism.io/issues/2610)). JavaScript tests files are not shown.

It was fixed for ECMAScript track by adding a `test_pattern` property in `config.json` file (see [xecmascript#65](https://github.com/exercism/xecmascript/pull/65/files)).

**Comment by kytrinyx** [comment]
+1, I just looked at this, and confirmed that adding the test_pattern property in the config will fix it.

**Comment by matthewmorgan** [comment]
Great, when should it deploy?  I checked just now and no test suite is visible in the GUI.

**Comment by kytrinyx** [comment]
I am deploying now.

**Comment by kytrinyx** [comment]
I've confirmed the fix.

**Comment by matthewmorgan** [comment]
😃
