### ISSUE TITLE
Make a distinction between JavaScript and ECMAScript tracks

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#161]
As discussed in [exercism.io#2750](https://github.com/exercism/exercism.io/issues/2750).

**Comment by rchavarria** [comment]
I wrote the proposed message in the exercism.io issue in the `docs/ABOUT.md` file.

It's still in [my fork](https://github.com/rchavarria/xjavascript/blob/make-distinction/docs/ABOUT.md) because I don't like it very much how the message is *highlighted*.

Would plain HTML work here @kytrinyx? Could I use HTML code instead of Markdown to highlight the message?

**Comment by kytrinyx** [comment]
Plain HTML is totally fine. I would use `_`, and put it at the bottom, also mentioning ECMAScript and how it would be different.

**Comment by rchavarria** [comment]
Do you think that italics will be enough?

Besides that, I'll follow your other suggestions.

**Comment by kytrinyx** [comment]
Yes, I think Italics will be enough.

**Comment by rchavarria** [comment]
Closed by #162
