### ISSUE TITLE
largest-series-product: Should tests test for implementation details (slices, digits)?

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#169]
Address discussion on [x-common#192](https://github.com/exercism/x-common/issues/192).

Check if this language track tests implementation details. If so, try to include some hints as in an [Elixir exercise](https://github.com/exercism/xelixir/tree/master/exercises/zipper/hints).

**Comment by matthewmorgan** [comment]
@rchavarria I think this is OK.  I made the same comment on the ES track.  Hope it's OK, I will merge both.

**Comment by rchavarria** [comment]
Yep, both checked :smile:
