### ISSUE TITLE
wordy: doesn't observe order of operations (PEMDAS)

### ISSUE THREAD

**Issue by s2tephen** [exercism/xjavascript#187]
```
xit('add then multiply', function() {
  var question = 'What is -3 plus 7 multiplied by -2?';
  expect(-8).toEqual(new WordProblem(question).answer());
});
```

This test case should really expect -17, but it could be argued that order of operations is out of the problem scope or should be included as a part 2/extension to the original task. Either way, whether or not PEMDAS is observed should be made clear in the readme.

**Comment by rchavarria** [comment]
In the [`README`](http://exercism.io/exercises/ecmascript/wordy/readme) you can find:

> ... you calculate as you move forward each step. 3 + 2 * 3 = 15, not 9.

So, I understand that we could write `What is -3 plus 7 multiplied by -2?` as `-3 + 7 * -2`, or `(-3 + 7) * -2`, so the result would be `-8`.

Please, if you find the `README` file confusing, just propose a clarifying message we can discuss or take this opportunity to modify the file yourself and submit a pull request, it'll be welcome.

**Comment by s2tephen** [comment]
Ah, you're right, looks like I glazed over that when I skimmed the read me. I guess I need to practice my reading comprehension rather than my coding 😝
Reading them again, the instructions are fine, but maybe explicitly adding "order of operations don't matter" might help clarify "you calculate as you move forward each step." I'll submit a PR.

**Comment by rchavarria** [comment]
LOL 
Thanks for you PR
