### ISSUE TITLE
anagram:  verify ordering of actual/expected

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#205]
In the Jasmine testing framework, it is convention to:

    expect(actual).fn(expected)

But some test suites have the following:

    expect(expected).fn(actual)

This causes the error messages to be confusing.

Please verify the anagram exercise to make sure that the expectations are ordered correctly. If they are, then this can be closed.

This issue will help to close #111

**Comment by ireddick** [comment]
I've got this one

**Comment by ireddick** [comment]
This one is OK and can be closed

**Comment by rchavarria** [comment]
Instead of commenting

> I've got this one

Can you assign issues to yourself? Personally, I don't know if you can, you might have no rights to do so, so excuse me if I'm asking for something impossible. In addition, I might be too late for asking this question.

BTW, many, many thanks!

**Comment by ireddick** [comment]
As far as I know, I can't assign issues to myself:

http://stackoverflow.com/questions/26752902/how-to-assign-issue-to-myself-at-github

**Comment by rchavarria** [comment]
Ok, so your comments are probably the best option. :+1:

**Comment by ireddick** [comment]
no worries :-)
