### ISSUE TITLE
etl:  verify ordering of actual/expected

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#218]
In the Jasmine testing framework, it is convention to:

    expect(actual).fn(expected)

But some test suites have the following:

    expect(expected).fn(actual)

This causes the error messages to be confusing.

Please verify the etl exercise to make sure that the expectations are ordered correctly. If they are, then this can be closed.

This issue will help to close #111

**Comment by ireddick** [comment]
Got this one

**Comment by ireddick** [comment]
This one is OK and can be closed

**Comment by rchavarria** [comment]
Great job!
