### ISSUE TITLE
linked-list: missing expectation

### ISSUE THREAD

**Issue by ireddick** [exercism/xjavascript#270]
The test 'deletes the only element' is missing an expectation.

Needs an expectation added, or the test deleted. Maybe check with other language tracks to see if the test exists there, and what is being asserted on?

**Comment by rchavarria** [comment]
Yep. The same exercise on xecmascript is:

    xit('deletes the only element', () => {
        const list = new LinkedList();
        list.push(10);
        list.delete(10);

        expect(list.count()).toBe(0);

    });

Feel free to create a PR including the `expect` line.

Very well caught.

**Comment by ireddick** [comment]
I've picked this up
