### ISSUE TITLE
meetup: use standard test naming format

### ISSUE THREAD

**Issue by ireddick** [exercism/xjavascript#271]
The test names in meetup don't use the same format as those in the other specs.

Example:

```javascript
it('test_monteenth_of_may_2013', function() {
  expect(meetupDay(2013, 4, 'Monday', 'teenth')).toEqual(new Date(2013, 4, 13));
});
```

I would expect this to be 'monteenth of may 2013'.

The test names were probably copied from the track for another language.

**Comment by rchavarria** [comment]
Absolutely, they look like ruby method names or so.

I like your *translation* to spec names, so if you don't mind, it would be great having a PR from you.

Thanks a lot for reviewing all specs, but not only that, but to actually read them and point out small issues like this one. Thanks a lot!

**Comment by ireddick** [comment]
I've picked this one up
