### ISSUE TITLE
Updated tests for the Custom Set problem

### ISSUE THREAD

**Issue by ryanplusplus** [exercism/xjavascript#283]
In order to reduce the amount of code required to pass incremental tests (assuming that users pass tests starting from the top), the order of the tests was modified slightly.

Since this track implements Custom Set, please take a look at the new custom-set.json file and see if your track should update its tests.

If you do need to update your tests, please refer to this issue in your PR. That helps us see which tracks still need to update their tests.

If your track is already up to date, go ahead and close this issue.

More details on this change are available in https://github.com/exercism/x-common/pull/257.

**Comment by ireddick** [comment]
Hi - I'm happy to pick this one up.

I've had a look through the JS test suite for this, and there isn't actually a discreet test that introduces set 
equality. The concept is introduced in the first test (delete element).

Current test order & method dependency (in brackets):                                                                                        

delete (eql)
difference (eql)
disjoint
empty (eql)
intersection (eql)
member
put (eql)
size
subset
toList
union (eql)

**Comment by ireddick** [comment]
working on a PR

**Comment by rchavarria** [comment]
Thanks @ireddick! Looking forward to seeing it.

**Comment by ireddick** [comment]
this isn't quite right:

- disjoint and equal are the wrong way around
- some test cases differ from those in canonical tests

I suggest that these are also fixed as part of the issue

Should I continue with this PR or start a new one?

**Comment by matthewmorgan** [comment]
Thanks for all your hard work.  Just make the changes on the same PR and push your changes.

In the end, we'll want you to squash to one commit before we merge, but don't worry about that until then!

**Comment by ireddick** [comment]
Apologies for the delay!

I've added a small commit that corrects the ordering of the 'disjoint' and 'equal' tests. This fixes the test ordering, which is what this issue and the parent PR are about.

However there are still differences from the the canonical custom-set.json test cases

https://github.com/exercism/x-common/blob/master/custom-set.json

'contains' is a good example (called "member" in this suite). The canonical test has the empty set case, for instance, yet this suite doesn't.

I'm going to put together a commit that fixes this, however I'm unsure about adding it to this PR, as this issue seems more focused on test ordering.

Advice needed - I'm happy to do it either way 🙂

**Comment by rchavarria** [comment]
I think that a single PR would be ok. The goal is to make the track as close as canonical tests as possible.

If that means reordering tests, that's ok. If that means renaming methods to match canonical tests, that's ok too.

@matthewmorgan? Any word on this?

**Comment by ireddick** [comment]
I've added a commit that adopts the test cases from the canonical tests.

There are now 2 outstanding things that I'd like to consider before squashing & merging this.

The 1st is whether or not empty sets should be constructed using an empty array or not, e.g.

`new CustomSet()`

vs.

`new CustomSet([])`

There were some of the latter before I started these changes, but I inadvertently added some more.
The former (no-args constructor) seems correct to me, and I'd like to change all empty set construction to use that.

The 2nd thing is the discrepancy of naming in a couple of method names, as mentioned earlier:

- 'member' in this track vs. 'contains' in the canonical tests
- 'put' in this track vs. 'add' in the canonical tests

I'm less sure about fixing this, but it is an opportunity to bring it in line.

Any advice welcome! 🙂

**Comment by rchavarria** [comment]
In other languages, I would keep the parameter in the constructor, to have homogeneous calls to it (the language might force me to do that). But, in JavaScript, I think the code is clearer without parameters in the constructor, so I'd use `new CustomSet()`.

About method names, I'd rename them to match canonical tests. `member` would become `contains`, and `put` would become `add`.

**Comment by ireddick** [comment]
I've added a further 2 commits that address those points - I think that this is now good enough.

Can someone give me an 'OK' on this?
(I'm assuming we'll be wanting to squash these still)

**Comment by rchavarria** [comment]
It looks good now. I have some comments about the code, but I'll make them in the PR #285
