### ISSUE TITLE
Rearrange left menu

### ISSUE THREAD

**Issue by AnnaGulstine** [exercism/xjavascript#288]
By placing "Installing JavaScript" above "Running the Tests," the flow would make more sense. This would clarify that node.js and jasmine-node need to be installed before trying to run any tests.

**Comment by rchavarria** [comment]
I agree, the flow would make more sense.

This is not a problem of this track (this repository). I've checked other languages and all of them have a similar left menu. I think this issue belongs to `x-common` repository.

But don't worry, let me ask @kytrinyx about this and we'll see what can be done.

**Comment by rchavarria** [comment]
@kytrinyx, all languages have a similar left menu, so it looks to me that there must be some code on `x-common` that renders it that way. I agree with @AnnaGulstine, I see that *Installing <language>* should appear before *Running the tests*, but I don't know if there is a reason for this order.

If you agree with the rearrangement and you don't find the time, just point us to the code we need to modify and we'll take care of it.

**Comment by kytrinyx** [comment]
This isn't in x-common, it's in https://github.com/exercism/exercism.io/blob/master/app/views/languages/language.erb#L13-L52

I agree with the rearrangement. I think I probably just didn't think through it too well when I originally made the page.

Is that enough information to make the change? (Also: thank you :heart:)

**Comment by AnnaGulstine** [comment]
Thank you for being so quick to respond! I submitted a pull request.

**Comment by rchavarria** [comment]
Great @AnnaGulstine! Awesome!

I'd like just to add a link to the PR, so that we know when this issue can be closed [exercism.io#2959](https://github.com/exercism/exercism.io/pull/2959).
