### ISSUE TITLE
Create an exercise generator for custom-set

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#292]
As discussed in #290, it would be nice to have exercise generators for exercises so that it would be easier to keep them in synch with canonical tests.

This issue's been created to discuss about the creation of the first of them.

**Comment by ireddick** [comment]
I've had a look at how this is being done for some of the other language tracks:

go - https://github.com/exercism/xgo#generating-test-cases

ruby - https://github.com/exercism/xruby/blob/master/README.md#generated-test-suites

scala - doesn't have anything in the readme

They are fairly different - for example, the ruby track has a file in /bin for each of the exercises, while the go track is simpler and keeps the exercise-specific files in the exercise dir. The scala track has a special top level dir dedicated to the whole thing called 'testgen'.

I'll start with a file in the exercise dir and see what comes of that - seems the simplest approach. Need to remember to use the magic 'example' prefix as noted: https://github.com/exercism/todo/issues/8#issue-70155154

**Comment by rchavarria** [comment]
I had in mind an idea similar to the scala approach. But it doesn't matter, let's start with a file in each exercise dir.

**Comment by ireddick** [comment]
I've spiked this, which you can take a look at over here: https://github.com/ireddick/xjavascript/commit/a21d753f46ed45bf4ad52af66f721f04b6f25ec1

You can run it from within the exercise dir with:

`node example-gen.js`

I've also added a generated spec file, 'example-gen-output.js', to show what it looks like.

From this, I think we can create something a little cleaner. I'm unsure about re-use at the moment, as I haven't looked to see how consistent the test case data is for the various exercises. I'm also noting that the purpose here isn't to write a generic generator https://github.com/exercism/todo/issues/8#issue-70155154

I have a few questions:

1) What about the existing non-canonical tests?

These are currently located at the end of the spec file. My suggestion is to continue to do this, but to run them through the generator for consistency. This would mean declaring them in the same form as the canonical test data, probably simply hard coded in the generator file.

2) Do we need to add a version number to the spec file?

See here in the ruby spec: https://github.com/exercism/xruby/blob/master/exercises/custom-set/example.rb#L98

3) Are we OK with using template literals?

They're an ES6 feature so it's *technically* breaking the "use the same language as the track" rule.

**Comment by rchavarria** [comment]
First of all, thanks for your work and sorry to reply so late.

> I'm also noting that the purpose here isn't to write a generic generator exercism/todo#8 (comment)

Yep. As I understand them, we would need a generator for each exercise. It will be easier to write them than write a generic one that generates all posible exercises. Let's focus on write a generator for each exercise.

I wouldn't be worried about code reuse. There is only one generator, the one you're working on. When more generators exist, we will think about code reuse.

> What about the existing non-canonical tests?

I think non-canonical tests exist mainly for these reasons:

1. They are language specific, and they make no sense in other languages
2. They are kind of duplicated test cases, and they are redundant
3. They are old test cases and nobody took the time to clean them

As you point out, there are two solutions:

1. Append them directly in the generator
2. Move them with the rest of canonical tests, this will affect other language tracks.

I agree with your suggestion, let's keep them in this track. You could create a issue in this track to have a reminder to move them with canonical tests if you want.

> Do we need to add a version number to the spec file?

I don't think so, I don't know what's the purpose of the version number in the ruby spec. Sorry.

> Are we OK with using template literals?

For me it's ok. It makes the code easier to write in this case. It's an ES6 feature, and this track is focused on features prior to ES6, but I don't think it will be problematic. The rule you talk about is to prevent writing these generators in ruby for a java track, for example. But a JavaScript developer would be happy to learn and use *template literals*.

**Comment by rchavarria** [comment]
I also have some comments about the code.

I would include some comments at the top of the file, explaining how to run the generator, or stating some restrictions.

There is no way to have a `README` file for each generator, so I would include some comments in them. For this particular generator, I would explain:

1. How to run it (the `node example-gen.js` is enough)
2. Minimum NodeJS version needed, because of *template literals* feature. It's not available in all versions of NodeJS.
3. The script needs `x-common` repository to be in a specific place in the file system, because the script reads a file from a specific path. Just to be sure that we don't forget to clone that repository or to update it before running the generator.

**Comment by ireddick** [comment]
Thanks for the feedback!

I'm working on a simpler, cleaner version that will include what you've suggested.

I'll check what the other tracks are doing with regard to ensuring that `x-common` is checked out and up to date.

**Comment by ireddick** [comment]
Apologies for the long delay - I'm pretty close to having a commit ready.

**Comment by rchavarria** [comment]
Great! Go, go, go!
