### ISSUE TITLE
Standardize filenames?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjavascript#30]
Now that we don't have any strict requirements with respect to filenames (aside from the fact that the example file has to be named something with `example`), it might be worth renaming so we don't have a mix of hyphens and underscores, e.g. `sum-of-multiples_test.spec.js`.

**Comment by rchavarria** [comment]
Finally, test filenames were changed to `<exercise>.spec.js` in PR #123.

Everything is fine to close this issue?

**Comment by kytrinyx** [comment]
Yepp, that looks good.
