### ISSUE TITLE
Difficulty: 1

### ISSUE THREAD

**Issue by almadsen** [exercism/xjavascript#302]
Why is the difficulty set to one in all of the "problems"?

**Comment by matthewmorgan** [comment]
@almadsen the 'difficulty' property is the beginning of a work in progress, recently made part of the metadata for each language track.

For this track, the exercises have yet to be ranked.  So, if you want to contribute by ranking them and making a PR, that would be awesome.

@rchavarria let me know if I have that right!

**Comment by almadsen** [comment]
I'll just might try that. Is there any idea of the grading system, ergo is the idea a difficulty from say 1-10 or is it more to guide to wish problem to choose next?

**Comment by rchavarria** [comment]
@almadsen You'll find an explanation of the work in progress on issue #299 

Yep, `difficulty` is meant to be an integer from 1 to 10. In theory, current exercises are more or less sorted on difficulty, so it would make no sense to rate the second one with a `10` and the last one with a `1`, but the rate will be a very subject value. Don't worry about that, it will generate nice conversations and learnings.

Probably, the most interesting property to have would be `topics`. Each exercise should have a `slug`, a `difficulty`, and `topics`. But it will require much more work. So contribute with the amount of work you want, anything will be more than wellcome.

**Comment by ldwoolley** [comment]
Acronym, has been one of the easiest so far.  Perhaps it deserves an easier score then it's position indicates.

**Comment by matthewmorgan** [comment]
I'm going to close this issue for now-- @almadsen if you want to make a PR around grading the exercises, please go for it.
