### ISSUE TITLE
Changes to Bowling tests

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xjavascript#303]
We recently rewrote the test suite for Bowling. Since this track implements Bowling, please [take a look at the new canonical_data.json file](https://github.com/exercism/x-common/blob/9049dc7f748fd038b140c878c4eaa89d09b73199/exercises/bowling/canonical-data.json) and see if your track should update its implementation or tests.

The new test suite reorders tests so that students can get to green quickly. It also reduces the number of tests so that students can focus on solving the interesting edge cases.

More details on this change are available in [this issue](https://github.com/exercism/x-common/issues/409)

**Comment by rchavarria** [comment]
This track needs to rewrite (maybe just reorder) the specs to match the canonical tests and tests order.

I'll label this issue as `good first patch` because it should be easy to perform these changes. 

If anyone decides to implement this, and a problem arises, please comment on this issues and ask for help.

**Comment by ldwoolley** [comment]
I can take this one, as a Second Patch.

**Comment by rchavarria** [comment]
I would prefer to keep raising errors. I think that returning `-1` is the way in x-common to specify an error must be returned. 

I've looked at other languages, and [ruby](https://github.com/exercism/xruby/blob/master/exercises/bowling/bowling_test.rb#L103) raises errors too, and [elixir](https://github.com/exercism/xelixir/blob/master/exercises/bowling/bowling_test.exs#L263) expects to get `:error` responses. Nothing about a `-1`. I would keep raising error is JavaScript. exercism/javascript, do you have some strong opinion on this?

**Comment by matthewmorgan** [comment]
@rchavarria I recall that `-1` in the `config.json` is a placeholder for [throwing and error or an exception](http://stackoverflow.com/questions/16142583/whats-the-different-between-error-and-exception-in-javascript), I think either solution would be acceptable in this context.

**Comment by ldwoolley** [comment]
Good.  I prefer the error throwing path.
