### ISSUE TITLE
word-count holds onto punctuation, while other languages clear punctuation.

### ISSUE THREAD

**Issue by ldwoolley** [exercism/xjavascript#305]
I noticed that java-script word-count requires maintaining the punctuation, while other languages like Python and Ruby test that punctuation has been removed.  Removing the punctuation in Javascript is relatively easy, and more like the other tests.  I recommend we make this change.  I can update the tests, if this path is chosen.

**Comment by rchavarria** [comment]
Sorry, I don't know what do you mean by:

> requires maintaining the punctuation

Do you mean that some tests force the implementation to keep punctuations from previous tests? If so, in my opinion, tests would be wrong. Tests should be independent, so punctuation should be *reset* from test to test. I mean, punctiation should be independent from test to test.

Can you show an example of a test you have in mind, please? Or, can you link to the Ruby or Python code that show what you mean?

**Comment by ldwoolley** [comment]
The  4th JavaScript test in word-count for the is called `'includes punctuation'` , while the same python test is called `test_ignores_punctuation`.  The test correct comparison lines for JavaScript include the punctuation in [expectedCounts](http://exercism.io/exercises/javascript/word-count/test-suite#L22), while the same[ assertEqual](http://exercism.io/exercises/python/word-count/test-suite#L37) in the python test does not include the `!!&@$%^&`.

These are exactly opposite.  I checked into the x-common directory and found that the reference test is defined as [ignoring the punctuation](https://github.com/exercism/x-common/blob/master/exercises/word-count/canonical-data.json#L31).   I just thought that JavaScript track might want to be consistent, and punctuation normally modifies the sentence rather than the word.  

Should we adjust the JavaScript track to match the x-common and other tracks for word-count?  I will make the submission.

**Comment by rchavarria** [comment]
Absolutely!

The issue is tremendously clear now. Thanks for such explanation (and links to just the right lines of code, I didn't know it was possible).

Yeah, go ahead, and make JavaScript x-common compliant.

**Comment by ldwoolley** [comment]
Now that Thanksgiving family activities are over, I will pick this up.
