### ISSUE TITLE
Adjust skeleton files to match exercise order

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xjavascript#318]
Right now `hello-world` and `bob` start with a skeleton file, but the [order of exercises](https://github.com/exercism/xjavascript/blob/master/config.json#L8-L12) has changed to 

0. hello-world
0. leap
0. hamming
0. rna-transcription
0. bob

It would probably be a good idea to remove the skeleton file from the Bob exercise, and add it to leap.

**Comment by joshuacolvin** [comment]
I can work on this if it's still available.

**Comment by rchavarria** [comment]
It's all yours. Thanks for showing up!

**Comment by joshuacolvin** [comment]
No problem. Glad to help. Let me know if I need to change anything.
