### ISSUE TITLE
No indication of skipped tests in main docs

### ISSUE THREAD

**Issue by mienaikage** [exercism/xjavascript#334]
'Running the tests' does not mention `xit` or `xdescribe`, and the installation steps currently gets you jasmine-node v1.14.3 which does not mark `xit` tests as skipped. The readme for the exercise does mention `xit` and `describe`, however someone who has already done the same exercise on another track (such as myself!) may go straight for the exercise and miss these details.

Test output from jasmine-node v1.14.3 suggests that you have completed an exercise even if it contains `xit` tests:
```
jasmine-node .
.

Finished in 0.005 seconds
1 test, 1 assertion, 0 failures, 0 skipped
```

jasmine-node v2 informs you that `xit` tests have been skipped:
```
jasmine-node .
.--

Finished in 0.004 seconds
3 Tests, 0 Failures, 2 Skipped
```

Should the installation instructions be updated to have `npm install jasmine-node@2 -g`? (I'm not very experienced with JavaScript so am unaware of any potential issues this could cause since it's beta). `docs/TESTS.md` should also be updated to mention `xit` and `xdescribe`.

**Comment by rchavarria** [comment]
If jasmine-node v2 is in beta, I'd rather keep v1.14.3. But I agree on updating `docs/TESTS.md` to include a note about `xit` and `xdescribe`.

Do you want to update that doc file? If so, I'd include the comment before the title "Making Your First Node Module". If not, don't worry, it's fine. I'm sure your idea will help lots of people.

**Comment by tejasbubane** [comment]
@mienaikage did not respond, hence I went ahead and did it along with some other changes.
