### ISSUE TITLE
JS Leap Year stub is confusing.

### ISSUE THREAD

**Issue by jeffreydking04** [exercism/xjavascript#337]
This is the stub:

```javascript
//
// This is only a SKELETON file for the "Leap" exercise. It's been provided as a
// convenience to get you started writing code faster.
//

var Year = function() {};

Year.prototype.isLeap = function(input) {
//
// YOUR CODE GOES HERE
//
};

module.exports = Year;
```

And this is the first test:

```
  it('is not very common', function() {
    var year = new Year(2015);
    expect(year.isLeap()).toBe(false);
  });
```

The tests are instantiating a new `Year` with the year as input and then calling `isLeap` without an input, but the stub has no parameters for `Year`, but looks for an input when `isLeap` is called. 

Was this intentional?

**Comment by matthewmorgan** [comment]
Hi @jeffreydking04 ,

This looks like an error in the stub file to me.  I _think_ this might reflect an older version of the exercise.

If you would like to submit a PR to revise this, that would be a welcome contribution!  Let me know how I can help.

**Comment by jeffreydking04** [comment]
Matt,


I will get that done this weekend.  


Jeffrey



-----Original Message-----

**Comment by joelwallis** [comment]
Hello, @matthewmorgan.

I've just stumbled upon this issue today, but I'm confused about how I should fix the stub file. The test suit assumes that the user will be using an object oriented style to solve the issue, but since it's a very simple issue (the very second one in the JavaScript track), probably focused on forcing the student to practice JS functions, should we really keep the OO-style instead of providing a function as the starting point of it?

E.g.:

```js
function isLeap (year) {
  // your code goes here
}

module.exports = isLeap
```

**Comment by joelwallis** [comment]
This PR changes the Leap exercise to use a function-based exercise, with updated test and stub files.

**Comment by joelwallis** [comment]
Ops! Forgot to rename the variable - but Travis caught it real quick 🤘

**Comment by joelwallis** [comment]
Sorry for the flooding. I just realized how the Exercism test works after reading the Makefile (that was the first time I read one)

**Comment by matthewmorgan** [comment]
@joelwallis thank you for your efforts, but we already have an open PR for this from @jeffreydking04  here https://github.com/exercism/xjavascript/pull/338

It's our mistake that there is no reference to that PR here.  There has been a bit of a delay in merging it, but the work is done.

Thanks again, and I hope you will contribute in the future!

**Comment by joelwallis** [comment]
@matthewmorgan no problem! Happy to see it happening!

Thanks for your feedback
