### ISSUE TITLE
There is no need for `jasmine-node` to run tests

### ISSUE THREAD

**Issue by rchavarria** [exercism/xjavascript#341]
According to [official Jasmine documentation](https://jasmine.github.io/pages/getting_started.html), there is a npm package called `jasmine`, that includes the Jasmine testing framework and can run your JavaScript tests.

It would be as easy as:

```
npm install jasmine
jasmine init
jasmine
```

It would be a good idea to update this track's documentation to reference `jasmine` instead of `jasmine-node` to run the tests.

Thanks @joelwallis for pointing this out on #315 

@exercism/javascript Any thoughts?

**Comment by joelwallis** [comment]
Hey!

Good to see it's in progress. I'm available to implement this change if you're willing to review my work :)

@exercism/javascript take a second to check if it's a good idea, and gimme a green flag so I can make a PR for this change.


PS: I've just `npm i -g jasmine`, then `jasmine ./my-solution-file.js`. There was no need to `jasmine init`.

**Comment by matthewmorgan** [comment]
@rchavarria @joelwallis I think this is great.  

I think that a global install is necessary to use the command line `jasmine`, and that we would need to change the directory structure.  So, I would propose we have two choices:

1. Tell the users to install globally, and use @joelwallis' approach, which requires a global install but no directory changes.  This is simple, but has the disadvantage that our dependencies are not all encapsulated in each exercise.

2. Add a `package.json` file to each exercise, similar to what we have in the Ecmascript track.  This would allow the users to change node versions easily and have their dependencies spelled out for each exercise.  It would also mean we could set up an npm `test` script, so the user doesn't need to type the filename each time.

@exercism/javascript any feeling about these two different approaches?

**Comment by tejasbubane** [comment]
> and that we would need to change the directory structure. So, I would propose we have two choices:

I did not get what change you are referring here @matthewmorgan

**Comment by rchavarria** [comment]
Option 2 (add `package.json`) seems desirable, because it could simplify the life to the users a little bit. But I don't like how we manage `package.json` files in xecmascript (but I don't have a better approach neither :sad: ). It needs to copy the same version of the file on each exercise, or manage a lot of almost identicall `package.json`, and I don't like those approaches.

Right now, in the documentation, we're suggesting to install `jasmine-node` globally, so as a first step, I'd do the same with `jasmine`.

I was a bit worried about `jasmine init` command. I don't know what that command does. Any clue? Anyway, @joelwallis says it works without executing that command.

**Comment by tejasbubane** [comment]
> I was a bit worried about jasmine init command. I don't know what that command does. Any clue? 

`jasmine init` creates this file in `spec/support/jasmine.json`:

```
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

Since we have `exercise.js` and `exercise.spec.js` in the same directory, we don't need this config.

**Comment by matthewmorgan** [comment]
Right @tejasbubane this is related to my comment about needing to change the directory structure if we want to just use the `jasmine` command without specifying a target.  It expects the spec files to be in `/spec` I think.

**Comment by tejasbubane** [comment]
> It expects the spec files to be in /spec I think.

@matthewmorgan Nope. It does not. 

With the current directory structure where:

```
$  ls
HINTS.md            example.js          hello-world.js      hello-world.spec.js
```

I can run `jasmine hello-world.spec.js` from the `hello-world` directory. Or I can even run `jasmine hello-world/hello-world.spec.js` from outside the `hello-world` directory.

**Comment by joelwallis** [comment]
@tejasbubane I think that @matthewmorgan was trying to say that, if we want students to test the lesson by just running `jasmine` - without arguments, the program itself would expected tests to be inside a `/spec` folder.

I believe it's kinda overwhelming for now. From an user perspective, executing `jasmine` against a test file makes more sense that just executing `jasmine` and having _some magic_ happening, without any clue about how it really happens. For me it makes me feel quite lost.

Btw, if we are going to support `package.json` files in exercise files we must embrace Node.js and its industry standards. I must:

- Provide a `package.json` for each lesson;
- Use [npm scripts](https://docs.npmjs.com/misc/scripts) to provide a standard way to test code (`npm test`);
- Perhaps running `npm install` right after `exercism fetch javascript` (is that possible?)

We could even use tools like gulp to provide file watching functionalities for students having their solution tested right after saving it, but this would only be possible if we support exercise-based `package.json` files.

**Comment by tejasbubane** [comment]
> We could even use tools like gulp to provide file watching functionalities for students having their solution tested right after saving it, but this would only be possible if we support exercise-based package.json files.

I am of the opinion of keeping it as simple as possible and not bring in build tools. Reasons being there is no standard one there, and they get outdated eventually.

Running against files seems more natural to me (maybe because I come from ruby where I run `rspec file-name.rb`).

**Comment by joelwallis** [comment]
I'm with you @tejasbubane. [KISS](https://en.wikipedia.org/wiki/KISS_principle).

**Comment by matthewmorgan** [comment]
@joelwallis[ has offered to work on this](https://github.com/exercism/xjavascript/issues/284#issuecomment-295865107), I'm inclined to say "do it!"  

@exercism/javascript unless there are any objections?  @joelwallis you will want to open a PR for 'dibs' on implementing this change.  It's simple, but touches a lot of files.  Please let me know if you want any help.

**Comment by rchavarria** [comment]
I agree with @tejasbubane: I prefer not having `package.json` on each exercise (it's causing lots of work on xecmascript, but it is *needed* in that track) and I prefer running tests specifying the spec file (`jasmine hello-world.spec.js`)

@joelwallis, it's all yours! We'll be happy to help on anything you need.

**Comment by joelwallis** [comment]
Awesome!

But, @matthewmorgan what did you mean with 'dibs'?

**Comment by tejasbubane** [comment]
@joelwallis [A claim to the right to use or enjoy something exclusively or before anyone else](https://en.wiktionary.org/wiki/dibs).

**Comment by joelwallis** [comment]
Roger that.

**Comment by matthewmorgan** [comment]
@joelwallis yeah it's an attempt to prevent what happened to you when you made the "duplicate" pr a few days ago.  :)

**Comment by ronalson** [comment]
@matthewmorgan and @joelwallis sorry for bring this issue back, but I'm getting an error when I use the `jasmine .` command within the /hello-word directory.

When I run `jasmine hello-world.spec.js` the test runs as expect.

However, when I run `jasmine .` as the README.md instruction says I'm getting this error:

```
module.js:471
    throw err;
    ^

Error: Cannot find module '/Users/*****/Desktop/exercism/javascript/hello-world'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/usr/local/lib/node_modules/jasmine/lib/jasmine.js:197:8)
    at runJasmine (/usr/local/lib/node_modules/jasmine/lib/command.js:125:11)
    at Command.run (/usr/local/lib/node_modules/jasmine/lib/command.js:55:9)
```

**Comment by joelwallis** [comment]
Hi, Ronalson.

Did you tried just running `jasmine`, without the forwarding dot?

Joel Wallis Jucá
joelwallis.com

**Comment by ronalson** [comment]
Hi Joel,

Nope, I haven't done it before. But I did it now and this is what I got:

```
Started

No specs found
Finished in 0.004 seconds
```

**Comment by joelwallis** [comment]
Thanks for reporting! I'll take a closer look on it tomorrow.

If you don't mind, open a new issue describing the problem you're facing,
alongside outputs you're getting from your errors, and the version of
Jasmine you're using.

Also, please mention me on a comment so I can be notified.

Joel Wallis Jucá
joelwallis.com
