### ISSUE TITLE
Update Jasmine config to make testing simpler -- should we?

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjavascript#351]
#349 pointed out that our current setup for testing does not allow the user to run the `jasmine` cli command without specifying a target test file.

The users could be able to just type `jasmine` in the terminal to run their tests.  In order to get Jasmine to do this, we need:

A `jasmine.json` file in `/exercises/spec`.  That file could look like this:

```javascript
{
    "spec_dir": ".",
    "spec_files": [
        "./*spec*",
    ]
}
```

And, an environment variable called `JASMINE_CONFIG_PATH` set to point to the `jasmine.json` file.

1. Is this worth pursuing?  Or is the current setup simple enough?
2. If #1, we may need to create a bash script that incorporates the JASMINE_CONFIG_PATH in the command, maybe like:

```bash
# test.sh

JASMINE_CONFIG_PATH=../spec/config/jasmine.json jasmine
```

As an alternative, we could forgo the config, and target the specfile using a pattern:

```bash
# test.sh

jasmine *spec.js
```

Then the users could just type `./test.sh`.

@exercism/javascript should we pursue this?  BTW if there is an easier way to set up the global config, I would be interested in hearing about that.  Seems like maybe we could configure a top-level `package.json` file, then use npm scripts to handle our config perhaps.

**Comment by joelwallis** [comment]
Hey @matthewmorgan, after reading the description of required steps I thought it would result an even more complex test environment. JavaScript students who are learning through Exercism are supposed to be able to run a simple command against a file. With that, being able to run `jasmine *.spec.js` is probably much simpler than setting up a config file, an env variable, etc., to just be able to run `jasmine` to get a test running.

I'm not sure if it worths the investment.

**Comment by matthewmorgan** [comment]
I am feeling the same way, just looking for a  reason _not_ to do this.  I think simpler is better.  I'll close this issue, anyone feeling strongly against it should re-open.
