### ISSUE TITLE
Replace <> with {} in TESTS.md file

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xjavascript#353]
I opened an issue on the [exercism.io](https://github.com/exercism/exercism.io/issues/3498) repo regarding odd rendering of the JavaScript TESTING.md file.  

There is text that looks like HTML tags that is confusing the renderer.  Let's replace `<EXERCISE>` etc with `{EXERCISE}`. 

This would be a great 'first time patch' so I'm going to label it that way.

Success criterion:
-  All patterns like this should be replaced in the MD file.

**Comment by tejasbubane** [comment]
Reference https://github.com/exercism/exercism.io/issues/3498 for more context.

**Comment by morrme** [comment]
This wouldn't be my first but if no one else steps up, I'm happy to help.

**Comment by tejasbubane** [comment]
Go ahead @morrme 👍
