### ISSUE TITLE
make test typically only runs the first test in the suite

### ISSUE THREAD

**Issue by drueck** [exercism/xjavascript#71]
I'm not sure if this has been addressed before, or if it's a big deal or not, but typically all but the first test in the suite are marked not to run by renaming `it` to `xit`. So, `make test` usually only runs the first test in each suite. If the goal of `make test` is to make sure the tests and example don't blow up and the example passes all the tests, then it might be nice to rename the `xit`s to `it` and then run the tests.

That might be trickier than it's worth, though? What do you think?

**Comment by kytrinyx** [comment]
I think it's worth it, but if we change all the `it` to `xit` then there's no good way to change them back without doing a `git reset`. This is fine on Travis, but in local development I would not be surprised if people want to run the tests as the very last thing after making changes, and now you have the potential for losing work or committing the test changes by accident.

**Comment by drueck** [comment]
Oh, I was just thinking of having the make script convert `xit` to `it` after it copies the example solution to the real solution filename in the temp directory. Then it could run all the tests, not just the first one. Those changes would be discarded because they would only exist in the temp directory, not in the actual repo directory.

I haven't done much shell scripting in a long time, but I could try to put something together that would do that. Does `make test` need to run on all platforms or just mac and linux?

**Comment by drueck** [comment]
I'd have to look at the `Makefile` again; I can't remember if it copies the tests to a temporary directory as well, or if it just copies and renames the example. If not, then we'd have to change the script to copy both the tests and the example to the temp directory so we could safely change the tests.

**Comment by kytrinyx** [comment]
> Those changes would be discarded because they would only exist in the temp directory, not in the actual repo directory.

Oh, of course. Yeah, that sounds gread.

> Does make test need to run on all platforms or just mac and linux?

I haven't the foggiest. @LegalizeAdulthood, do you know about this?

**Comment by LegalizeAdulthood** [comment]
IIRC, the JS tests are all executed with NodeJS and that is cross-platform.  So it is possible to run it on Windows, but I haven't tried outside the perspective of running my own tests while working on a JS exercise.

**Comment by drueck** [comment]
Thanks for the feedback, @LegalizeAdulthood. I was more talking about running the `make test` script in the Makefile. I know that is primarily designed to be run on Travis, but it's also nice to be able to run it locally on your development machine if you're developing a new exercise or modifying an existing one. But yeah, I'd assume running make on Windows would require installing a bunch of stuff that the average Windows user doesn't have installed, right? Probably not necessary to support that use case?

**Comment by LegalizeAdulthood** [comment]
The Makefile as it stands assumes a unix like environment.  It would probably work fine with a cygwin bash shell.

**Comment by drueck** [comment]
Yeah, good point.  :)
