### ISSUE TITLE
Clarification regarding bob_test.spec

### ISSUE THREAD

**Issue by purezen** [exercism/xjavascript#77]
Guys, is this spec correct?
xit("calmly speaking about umlauts", function() {
    var result = bob.hey("\xfcML\xe4\xdcTS");
    expect(result).toEqual('Whatever.');
  });

Ref: https://github.com/exercism/xjavascript/blob/master/bob/bob_test.spec.js#L61

My understanding says that since the input here has capital letters, they signify yelling at Bob and so the expected result must be "Whoa, chill out!".

**Comment by kytrinyx** [comment]
For something to be considered shouting all the characters need to be uppercase, and here the word is mixed case.

**Comment by kytrinyx** [comment]
Would it help to have a comment next to it that shows the actual characters the way they would be translated?

E.g.

```
var result = bob.hey("\xfcML\xe4\xdcTS"); # üMLäÜTS
```
