### ISSUE TITLE
crypto-square: missing test-case

### ISSUE THREAD

**Issue by schorsch3000** [exercism/xjavascript#89]
Hi,
there is a missing testcase for size() that tests that the square is calculated against the filtered input, not the original input.

the size of ("1 2 3 4") should be 2 not 3.
all tests which test size are with valid chars only.

if wished, i could write this test and create a pull-request.

**Comment by kytrinyx** [comment]
That would be great, thank you!

**Comment by ZacharyRSmith** [comment]
This seems to have been addressed. This test is in the current suite:
```javascript
  xit("size of small square with additional non-nuber chars",function() {
    var crypto = new Crypto('1 2 3 4');
    expect(crypto.size()).toEqual(2);
  });
```

**Comment by kytrinyx** [comment]
Yepp, that looks right. Thanks!
