### ISSUE TITLE
Incorrect expectations in "grains" exercise

### ISSUE THREAD

**Issue by nonsensery** [exercism/xjavascript#91]
In the "grains" exercise, we are asked to write code to calculate the number of grains on the tiles of a chess board where, for the nth tile, the number of grains is 2^(n-1). Since a chess board has 64 squares, that means the final square will have a value of 2^63 (`9223372036854775808`) grains. However, in JavaScript, integers are represented as 64-bit floating point numbers, so they cannot accurately represent this number. For example:

```js
console.log(9223372036854775808);
// =>       9223372036854776000
//                         ^^^^
```

The tests do not take this into account:

```js
  it("square 64", function () {
    expect(grains.square(64)).toEqual(9223372036854775808);
    // => Test is expecting value to equal 9223372036854776000
  });

  it("total", function () {
    expect(grains.total()).toEqual(18446744073709551615);
    // => Test is expecting value to equal 18446744073709552000
  });
```

My guess is that solving this "for real" is outside of the intended scope, since it would require the use of some sort of "big integer" type. Instead, it might make sense to alter the exercise to use a smaller board. The total for a 7x7 board (`562949953421311`) is well within the 2^53 limit for JavaScript integers, but 7x7 is kind of a strange size. Maybe 6x6?

**Comment by nonsensery** [comment]
I suppose another option would be to provide a big integer module in the exercise code. Some options:
- [strint](https://github.com/rauschma/strint)
- [javascript-biginteger](https://github.com/silentmatt/javascript-biginteger)
- [BigInteger.js](https://github.com/peterolson/BigInteger.js)

**Comment by kytrinyx** [comment]
In other language tracks the solutions use BigInteger types. I think it would make sense to include one of these for this problem. Do you have any preferences?

**Comment by nonsensery** [comment]
It seems like [BigInteger.js](https://github.com/peterolson/BigInteger.js) might be a good choice. It has a sane API, and (more importantly) is licensed as public domain.

[Here's a gist with a sample solution](https://gist.github.com/nonsensery/1b48da5316a092dc7312) (I've installed the `big-integer` module using npm).

**Comment by kytrinyx** [comment]
Yeah, I think it would be easier if we included the file. Anything to reduce the friction of having to figure out external dependencies.

**Comment by ZacharyRSmith** [comment]
#98 closes this

**Comment by kytrinyx** [comment]
Thanks, @ZacharyRSmith
